### PR TITLE
Frontend bug fix

### PR DESCRIPTION
**Pull request by Rangkynsai**
It fixed the issues #2
###changes proposed pull request
It fixed the bug of the front end in which the continuity of the scroll bar after the footer is fixed.

### CODE REVIEW

**Comment by Rangkynsai** [comment]
please review and merge my contribution #9 Thank you.

**Comment by sscodes** [comment]
Hello! Do the changes you have made resolve the "continuation after the footer section" issue? Because that was the only bug left to debugged, rest bugs were debugged by the previous debuggers.

**Comment by sscodes** [comment]
@Rangkynsai It would be better if you can send me a screenshot here of what the page looks like after your changes are made!

**Comment by Rangkynsai** [comment]
@sscodes i have made another pull request actually i have debug from yesterday so. Screenshot
image

**Comment by Rangkynsai** [comment]
@sscodes Actually i have debug from yesterday but i have made another pull request #10  Screenschot
image

Thankyou

**Comment by sscodes** [comment]
By the way, are you there on Linkedin?

**Comment by Rangkynsai** [comment]
no till now i don't have a linkedin account.

**Comment by Rangkynsai** [comment]
please review and merge my contribution Thankyou.

**Comment by sscodes** [comment]
yeah I have merged the other PR u had sent. I thought u intended me to do that becoz u might have made some modifications in that after doing in this.

**Comment by Rangkynsai** [comment]
Thank you i would love to contribute more like this

**Comment by sscodes** [comment]
Ya Sure!!

**Pull request merged**
